-- AlterTable
ALTER TABLE "CrytoDeposit" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Settings" ALTER COLUMN "max_withdraw" SET DEFAULT 25000,
ALTER COLUMN "max_withdraw" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "min_deposit" SET DEFAULT 500,
ALTER COLUMN "min_deposit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "min_withdraw" SET DEFAULT 500,
ALTER COLUMN "min_withdraw" SET DATA TYPE DOUBLE PRECISION;
